package icu4c

import (
	"encoding/hex"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// mongoLocales is the set of collation locales MongoDB 8.0 accepts (109 ICU
// locale IDs, from the MongoDB manual). The trimmed data blob must reproduce
// every one's collation exactly.
var mongoLocales = []string{
	"af", "sq", "am", "ar", "hy", "as", "az", "bn", "be", "bs", "bs_Cyrl", "bg",
	"my", "ca", "chr", "zh", "zh_Hant", "hr", "cs", "da", "nl", "dz", "en",
	"en_US", "en_US_POSIX", "eo", "et", "ee", "fo", "fil", "fi", "fr", "fr_CA",
	"gl", "ka", "de", "de_AT", "el", "gu", "ha", "haw", "he", "hi", "hu", "is",
	"ig", "smn", "id", "ga", "it", "ja", "kl", "kn", "kk", "km", "kok", "ko",
	"ky", "lkt", "lo", "lv", "ln", "lt", "dsb", "lb", "mk", "ms", "ml", "mt",
	"mr", "mn", "ne", "se", "nb", "nn", "or", "om", "ps", "fa", "fa_AF", "pl",
	"pt", "pa", "ro", "ru", "sr", "sr_Latn", "si", "sk", "sl", "es", "sw", "sv",
	"ta", "te", "th", "bo", "to", "tr", "uk", "hsb", "ur", "ug", "vi", "wae",
	"cy", "yi", "yo", "zu",
}

// fpProbes are tailoring-sensitive strings (accents, digraphs, CJK), stored as
// explicit code points. A locale's fingerprint is the sort keys of these; if a
// trim drops the locale's tailoring, the collator falls back to root and the
// keys change.
var fpProbes = []string{
	"a", "z",
	"\u00e5", "\u00e4", "\u00f6", "\u00fc", // a-ring, a-umlaut, o-umlaut, u-umlaut
	"\u00e6", "\u00f8", "\u0107", // ae-lig, o-slash, c-acute
	"ch", "ll",
	"\u4e2d\u6587", // CJK: zhongwen
}

func localeFingerprint(t *testing.T, locale string) string {
	t.Helper()
	parts := make([]string, len(fpProbes))
	for i, p := range fpProbes {
		k, err := SortKey(locale, p)
		if err != nil {
			t.Fatalf("SortKey(%q, %q): %v", locale, p, err)
		}
		parts[i] = hex.EncodeToString(k)
	}
	return strings.Join(parts, ",")
}

func fingerprintFile() string {
	return filepath.Join("testdata", "locale_fingerprints.txt")
}

// TestMongoLocaleFingerprints pins each MongoDB locale's collation as a golden
// fingerprint. Generated (UPDATE_LOCALES=1) from full ICU data; after the data
// blob is trimmed to collation-only, this must still match -- proving no
// locale's tailoring was dropped.
func TestMongoLocaleFingerprints(t *testing.T) {
	if got, want := len(mongoLocales), 109; got != want {
		t.Fatalf("locale list has %d entries, want %d", got, want)
	}

	current := make(map[string]string, len(mongoLocales))
	for _, loc := range mongoLocales {
		current[loc] = localeFingerprint(t, loc)
	}

	if os.Getenv("UPDATE_LOCALES") == "1" {
		var b strings.Builder
		b.WriteString("# ICU collation fingerprints (sort keys of tailoring probes) per MongoDB locale.\n")
		b.WriteString("# Generated by TestMongoLocaleFingerprints with UPDATE_LOCALES=1; the trimmed\n")
		b.WriteString("# data blob must reproduce these exactly. Format: locale<TAB>hexkey,hexkey,...\n")
		locs := append([]string(nil), mongoLocales...)
		sort.Strings(locs)
		for _, loc := range locs {
			b.WriteString(loc)
			b.WriteByte('\t')
			b.WriteString(current[loc])
			b.WriteByte('\n')
		}
		if err := os.MkdirAll("testdata", 0o755); err != nil {
			t.Fatalf("mkdir testdata: %v", err)
		}
		if err := os.WriteFile(fingerprintFile(), []byte(b.String()), 0o644); err != nil {
			t.Fatalf("write fingerprints: %v", err)
		}
		t.Logf("wrote %s for %d locales", fingerprintFile(), len(mongoLocales))
		return
	}

	golden := make(map[string]string)
	data, err := os.ReadFile(fingerprintFile())
	if err != nil {
		t.Fatalf("reading golden fingerprints (generate with UPDATE_LOCALES=1): %v", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if loc, fp, ok := strings.Cut(line, "\t"); ok {
			golden[loc] = fp
		}
	}

	changed := 0
	for _, loc := range mongoLocales {
		switch {
		case golden[loc] == "":
			t.Errorf("%s: missing from golden (regenerate with UPDATE_LOCALES=1)", loc)
		case golden[loc] != current[loc]:
			t.Errorf("%s: collation fingerprint changed -- trimming altered this locale", loc)
			changed++
		}
	}
	if changed > 0 {
		t.Errorf("%d/%d locales changed collation after trimming", changed, len(mongoLocales))
	}
}
